import { chromium } from '@playwright/test'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1280, height: 720 } })
await p.goto('http://localhost:3014/')
await p.getByRole('button', { name: '登录', exact: true }).click()
const d = p.getByRole('dialog', { name: '登录 Cue' })
await d.getByLabel('用户名', { exact: true }).fill('tester')
await d.getByLabel('密码', { exact: true }).fill('secret')
await d.getByRole('button', { name: '登录', exact: true }).click()
await d.waitFor({ state: 'hidden' })
const row = p.getByRole('button', { name: '亚麻衬衫二剪', exact: true })
await row.waitFor()
await row.hover()
await p.getByRole('button', { name: '亚麻衬衫二剪 的更多操作' }).click()
await p.getByRole('menuitem', { name: '删除' }).waitFor()
await p.waitForTimeout(200)
await p.screenshot({ path: '../probe-menu.png', clip: { x: 0, y: 200, width: 500, height: 340 } })
// 行内重命名
await p.keyboard.press('Escape')
await row.hover()
await p.getByRole('button', { name: '重命名 亚麻衬衫二剪' }).click()
await p.waitForTimeout(200)
await p.screenshot({ path: '../probe-rename.png', clip: { x: 0, y: 220, width: 264, height: 140 } })
await b.close()
